// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://somewhere.com/",
        "contact": {
            "name": "API Support",
            "url": "http://somewhere.com/support",
            "email": "support@somewhere.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Create User Auth",
                "operationId": "Create User Auth",
                "parameters": [
                    {
                        "description": "User to be created",
                        "name": "Case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserAdminInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login",
                "operationId": "Login User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "organization",
                        "name": "organization",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/casesubtypes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "List CasesSubType",
                "operationId": "ListCaseSubTypes",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/casesubtypes/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "Create CaseSubType",
                "operationId": "Create CaseSubType",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CaseSubTypeInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/casesubtypes/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "Delete CaseSubType",
                "operationId": "Delete CaseSubType",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "Update CaseSubType",
                "operationId": "Update CaseSubType",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CaseSubTypeUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/casetypes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "List Cases",
                "operationId": "ListCaseTypes",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/casetypes/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "Create CaseType",
                "operationId": "Create CaseType",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CaseTypeInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/casetypes/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "Delete CaseType",
                "operationId": "Delete CaseType",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cases"
                ],
                "summary": "Update CaseType",
                "operationId": "Update CaseType",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CaseTypeUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/commands": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Get Commands",
                "operationId": "Get Commands",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/commands/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Create Commands",
                "operationId": "Create Commands",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CommandInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/commands/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Get Commands by id",
                "operationId": "Get Commands by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Delete Commands",
                "operationId": "Delete Commands",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Update Commands",
                "operationId": "Update Commands",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CommandUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/departments": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Get Department",
                "operationId": "Get Department",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/departments/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Create Department",
                "operationId": "Create Department",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DepartmentInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/departments/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Get Department by ID",
                "operationId": "Get Department by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Delete Department",
                "operationId": "Delete Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Update Department",
                "operationId": "Update Department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DepartmentUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/forms": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Get Form",
                "operationId": "Get Form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "version",
                        "name": "version",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Create Form",
                "operationId": "Create Form",
                "parameters": [
                    {
                        "description": "Created Data",
                        "name": "Case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FormInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/forms/active": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Update Form Status",
                "operationId": "Update Form Status",
                "parameters": [
                    {
                        "description": "Update Data",
                        "name": "Case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FormActive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/forms/lock": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Update Form Lock",
                "operationId": "Update Form Lock",
                "parameters": [
                    {
                        "description": "Update Data",
                        "name": "Case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FormLock"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/forms/publish": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Update Form Publish",
                "operationId": "Update Form Publish",
                "parameters": [
                    {
                        "description": "Update Data",
                        "name": "Case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FormPublish"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Delete Form",
                "operationId": "Delete Form",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{uuid}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Update Form",
                "operationId": "Update Form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Data",
                        "name": "Case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FormUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/delete/{id}": {
            "delete": {
                "description": "ลบ Notification ตาม id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "delete notification by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/edit/{id}": {
            "put": {
                "description": "เเก้ไข Notification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "edit notification (partial input)",
                "parameters": [
                    {
                        "description": "Partial Notification Input",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Notification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Notification"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/new": {
            "post": {
                "description": "Create a notification by providing only partial fields. The remaining fields (e.g., ID, caseId, createdAt) will be generated automatically.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Create notification (partial input)",
                "parameters": [
                    {
                        "description": "Partial Notification Input (Do not include: id, caseId, createdAt)",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Notification"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Notification"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/noti/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Get notification by ID from database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Notification"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/recipient/{username}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Get notifications received by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username of the recipient",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Notification"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/notifications/ws": {
            "get": {
                "description": "Opens a WebSocket connection and listens for a username from the client to register for real-time notifications.",
                "tags": [
                    "Notifications"
                ],
                "summary": "WebSocket endpoint for real-time notifications by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username used to establish WebSocket connection",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols (WebSocket Upgrade)"
                    },
                    "400": {
                        "description": "Missing or invalid username query parameter",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error or WebSocket upgrade failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/stations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Get Stations",
                "operationId": "Get Stations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/stations/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Create Stations",
                "operationId": "Create Stations",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StationInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/stations/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Get Stations by id",
                "operationId": "Get Stations  by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Delete Stations",
                "operationId": "Delete Stations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dispatch"
                ],
                "summary": "Update Stations",
                "operationId": "Update Stations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StationUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User",
                "operationId": "Get User",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "operationId": "Create User",
                "parameters": [
                    {
                        "description": "User to be created",
                        "name": "Case",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/username/{username}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User by username",
                "operationId": "Get User by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User by Id",
                "operationId": "Get User by Id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_contacts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User with contacts",
                "operationId": "Get User with contacts",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_contacts/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User with contacts",
                "operationId": "Create User with contacts",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserContactInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_contacts/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User with contacts by id",
                "operationId": "Get User with contacts by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete User with contacts",
                "operationId": "Delete User with contacts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User with contacts",
                "operationId": "Update User with contacts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserContactInsertUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_skills": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User with skills",
                "operationId": "Get User with skills",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_skills/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User with skill",
                "operationId": "Create User with skill",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserSkillInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_skills/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User with skills by id",
                "operationId": "Get User with skills by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete User with skill",
                "operationId": "Delete User with skill",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User with skill",
                "operationId": "Update User with skill",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserSkillUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_socials": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User with socials",
                "operationId": "Get User with socials",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "start",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "length",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_socials/add": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User with socials",
                "operationId": "Create User with socials",
                "parameters": [
                    {
                        "description": "Create Data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserSocialInsert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/users_with_socials/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User with Socials by id",
                "operationId": "Get User with Socials by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete User with socials",
                "operationId": "Delete User with socials",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update User with socials",
                "operationId": "Update User with socials",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update data",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserSocialUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form and Workflow"
                ],
                "summary": "Get Workflow",
                "operationId": "Get Workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Request successful",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CaseSubTypeInsert": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "caseSla": {
                    "type": "string"
                },
                "en": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "sTypeCode": {
                    "type": "string"
                },
                "th": {
                    "type": "string"
                },
                "typeId": {
                    "type": "string"
                },
                "unitPropLists": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userSkillList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wfId": {
                    "type": "string"
                }
            }
        },
        "model.CaseSubTypeUpdate": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "caseSla": {
                    "type": "string"
                },
                "en": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "sTypeCode": {
                    "type": "string"
                },
                "th": {
                    "type": "string"
                },
                "unitPropLists": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "userSkillList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wfId": {
                    "type": "string"
                }
            }
        },
        "model.CaseTypeInsert": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "en": {
                    "type": "string"
                },
                "th": {
                    "type": "string"
                }
            }
        },
        "model.CaseTypeUpdate": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "en": {
                    "type": "string"
                },
                "th": {
                    "type": "string"
                }
            }
        },
        "model.CommandInsert": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Active status",
                    "type": "boolean"
                },
                "deptId": {
                    "description": "Department ID",
                    "type": "string"
                },
                "en": {
                    "description": "English name",
                    "type": "string"
                },
                "th": {
                    "description": "Thai name",
                    "type": "string"
                }
            }
        },
        "model.CommandUpdate": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Active status",
                    "type": "boolean"
                },
                "deptId": {
                    "description": "Department ID",
                    "type": "string"
                },
                "en": {
                    "description": "English name",
                    "type": "string"
                },
                "th": {
                    "description": "Thai name",
                    "type": "string"
                }
            }
        },
        "model.DepartmentInsert": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Active status",
                    "type": "boolean"
                },
                "en": {
                    "description": "English name",
                    "type": "string"
                },
                "th": {
                    "description": "Thai name",
                    "type": "string"
                }
            }
        },
        "model.DepartmentUpdate": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Active status",
                    "type": "boolean"
                },
                "en": {
                    "description": "English name",
                    "type": "string"
                },
                "th": {
                    "description": "Thai name",
                    "type": "string"
                }
            }
        },
        "model.FormActive": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "formId": {
                    "type": "string"
                }
            }
        },
        "model.FormInsert": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "formColSpan": {
                    "type": "integer"
                },
                "formFieldJson": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "formName": {
                    "type": "string"
                },
                "locks": {
                    "type": "boolean"
                },
                "publish": {
                    "type": "boolean"
                }
            }
        },
        "model.FormLock": {
            "type": "object",
            "properties": {
                "formId": {
                    "type": "string"
                },
                "locks": {
                    "type": "boolean"
                }
            }
        },
        "model.FormPublish": {
            "type": "object",
            "properties": {
                "formId": {
                    "type": "string"
                },
                "publish": {
                    "type": "boolean"
                }
            }
        },
        "model.FormUpdate": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "formColSpan": {
                    "type": "integer"
                },
                "formFieldJson": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "formName": {
                    "type": "string"
                },
                "locks": {
                    "type": "boolean"
                },
                "publish": {
                    "type": "boolean"
                }
            }
        },
        "model.Notification": {
            "type": "object",
            "properties": {
                "caseDetail": {
                    "type": "string"
                },
                "caseId": {
                    "type": "string"
                },
                "caseType": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "eventType": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "recipient": {
                    "type": "string"
                },
                "redirectURL": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "desc": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.StationInsert": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Active status\\",
                    "type": "boolean"
                },
                "commId": {
                    "description": "Community ID",
                    "type": "string"
                },
                "deptId": {
                    "description": "Department ID",
                    "type": "string"
                },
                "en": {
                    "description": "English name",
                    "type": "string"
                },
                "th": {
                    "description": "Thai name",
                    "type": "string"
                }
            }
        },
        "model.StationUpdate": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "Active status\\",
                    "type": "boolean"
                },
                "commId": {
                    "description": "Community ID",
                    "type": "string"
                },
                "deptId": {
                    "description": "Department ID",
                    "type": "string"
                },
                "en": {
                    "description": "English name",
                    "type": "string"
                },
                "th": {
                    "description": "Thai name",
                    "type": "string"
                }
            }
        },
        "model.UserAdminInput": {
            "type": "object",
            "properties": {
                "activationToken": {
                    "type": "string"
                },
                "active": {
                    "type": "boolean"
                },
                "address": {
                    "description": "Assumes JSON column",
                    "type": "string"
                },
                "blood": {
                    "type": "string"
                },
                "bod": {
                    "type": "string"
                },
                "citizenId": {
                    "type": "string"
                },
                "commId": {
                    "type": "string"
                },
                "deptId": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "empId": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "islogin": {
                    "type": "boolean"
                },
                "lastActivationRequest": {
                    "type": "integer"
                },
                "lastLogin": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "lostPasswordRequest": {
                    "type": "integer"
                },
                "middleName": {
                    "type": "string"
                },
                "mobileNo": {
                    "type": "string"
                },
                "orgId": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "signupStamp": {
                    "type": "integer"
                },
                "stnId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "userType": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserContactInsert": {
            "type": "object",
            "properties": {
                "contactAddr": {},
                "contactName": {
                    "type": "string"
                },
                "contactPhone": {
                    "type": "string"
                },
                "orgId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserContactInsertUpdate": {
            "type": "object",
            "properties": {
                "contactAddr": {},
                "contactName": {
                    "type": "string"
                },
                "contactPhone": {
                    "type": "string"
                }
            }
        },
        "model.UserInput": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "address": {
                    "description": "Assumes JSON column",
                    "type": "string"
                },
                "blood": {
                    "type": "string"
                },
                "bod": {
                    "type": "string"
                },
                "citizenId": {
                    "type": "string"
                },
                "commId": {
                    "type": "string"
                },
                "deptId": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "empId": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "islogin": {
                    "type": "boolean"
                },
                "lastActivationRequest": {
                    "type": "integer"
                },
                "lastLogin": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "lostPasswordRequest": {
                    "type": "integer"
                },
                "middleName": {
                    "type": "string"
                },
                "mobileNo": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "signupStamp": {
                    "type": "integer"
                },
                "stnId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "userType": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserSkillInsert": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "orgId": {
                    "type": "string"
                },
                "skillId": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "model.UserSkillUpdate": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "skillId": {
                    "type": "string"
                }
            }
        },
        "model.UserSocialInsert": {
            "type": "object",
            "properties": {
                "orgId": {
                    "type": "string"
                },
                "socialId": {
                    "type": "string"
                },
                "socialName": {
                    "type": "string"
                },
                "socialType": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserSocialUpdate": {
            "type": "object",
            "properties": {
                "orgId": {
                    "type": "string"
                },
                "socialId": {
                    "type": "string"
                },
                "socialName": {
                    "type": "string"
                },
                "socialType": {
                    "type": "string"
                },
                "updatedBy": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "CMS API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
